// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAdapter.Infrastructure;

#nullable disable

namespace SMEAdapter.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250718125514_Propertiesmadenullable")]
    partial class Propertiesmadenullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ManufacturerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("SMEAdapter.Domain.Entities.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("SMEAdapter.Domain.Entities.AssetSpecificProperty", "AssetSpecificProperties", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Key");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductAssetSpecificProperties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsMany("SMEAdapter.Domain.Entities.Marking", "Markings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Key")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Key");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Value");

                            b1.HasKey("Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductMarkings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.ProductIdentification", "ProductIdentification", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryOfOrigin")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_CountryOfOrigin");

                            b1.Property<DateTime?>("DateOfManufacture")
                                .HasColumnType("datetime2")
                                .HasColumnName("ProductId_DateOfManufacture");

                            b1.Property<string>("FirmwareVersion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_FirmwareVersion");

                            b1.Property<string>("HardwareVersion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_HardwareVersion");

                            b1.Property<string>("SerialNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_SerialNumber");

                            b1.Property<string>("SoftwareVersion")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_SoftwareVersion");

                            b1.Property<string>("URIOfTheProduct")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_URI");

                            b1.Property<string>("UniqueFacilityIdentifier")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductId_UniqueFacilityIdentifier");

                            b1.Property<int?>("YearOfConstruction")
                                .HasColumnType("int")
                                .HasColumnName("ProductId_YearOfConstruction");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.ProductInfo", "ProductInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ArticleNumber")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ArticleNumber");

                            b1.Property<string>("OrderCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_OrderCode");

                            b1.Property<string>("ProductDesignation")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductDesignation");

                            b1.Property<string>("ProductFamily")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductFamily");

                            b1.Property<string>("ProductRoot")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductRoot");

                            b1.Property<string>("ProductType")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductType");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("AddressInfo");

                    b.Navigation("AssetSpecificProperties");

                    b.Navigation("Markings");

                    b.Navigation("ProductIdentification");

                    b.Navigation("ProductInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
