// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAdapter.Infrastructure;

#nullable disable

namespace SMEAdapter.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251114151415_MiltiLangSet")]
    partial class MiltiLangSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManufacturerName");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDocuments");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("SMEAdapter.Domain.Entities.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.ProductInfo", "ProductInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ArticleNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ArticleNumber");

                            b1.Property<string>("OrderCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_OrderCode");

                            b1.Property<string>("ProductDesignation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductDesignation");

                            b1.Property<string>("ProductFamily")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductFamily");

                            b1.Property<string>("ProductRoot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductRoot");

                            b1.Property<string>("ProductType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductType");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("AddressInfo")
                        .IsRequired();

                    b.Navigation("ProductInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocument", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.Product", "Product")
                        .WithMany("Documents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentClassification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ClassDescription")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ClassId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ClassLang")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ClassName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ClassificationSystem")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DomainId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ValueId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentVersion", "Version", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Keywords")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Language")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("OrganisationName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("OrganisationOfficialName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<DateTime?>("StateDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Summary")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("Version")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.Navigation("Classification")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
