// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAdapter.Infrastructure;

#nullable disable

namespace SMEAdapter.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251217201106_TechnicalDataTemplate")]
    partial class TechnicalDataTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManufacturerName");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ManufacturerName");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDocuments");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocumentAssignment", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "ProductDocumentId");

                    b.HasIndex("ProductDocumentId");

                    b.ToTable("ProductDocumentAssignments", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TemplateId");

                    b.ToTable("ProductTechnicalData", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalDataProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomPropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomSemanticId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCustomProperty")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductTechnicalDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplatePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTechnicalDataId");

                    b.HasIndex("TemplatePropertyId");

                    b.ToTable("ProductTechnicalDataProperties", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TechnicalDataTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdtaSubmodelId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalDataTemplates", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SemanticId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("TemplateProperties", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SemanticId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateSections", (string)null);
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Company", b =>
                {
                    b.OwnsOne("SMEAdapter.Domain.Entities.CompanyAddressInfo", "CompanyAddressInfo", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("CompanyAddressInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("SMEAdapter.Domain.Entities.AddressInfo", "AddressInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.ProductInfo", "ProductInfo", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ArticleNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ArticleNumber");

                            b1.Property<string>("OrderCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_OrderCode");

                            b1.Property<string>("ProductDesignation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductDesignation");

                            b1.Property<string>("ProductFamily")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductFamily");

                            b1.Property<string>("ProductRoot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductRoot");

                            b1.Property<string>("ProductType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ProductInfo_ProductType");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("AddressInfo")
                        .IsRequired();

                    b.Navigation("ProductInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocument", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.Product", "Product")
                        .WithMany("Documents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentClassification", "Classification", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ClassDescription")
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ClassId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ClassLang")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("ClassName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Classification_ClassName");

                            b1.Property<string>("ClassificationSystem")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentIdentifier", "Identifier", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DomainId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ValueId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.OwnsOne("SMEAdapter.Domain.Entities.DocumentVersion", "Version", b1 =>
                        {
                            b1.Property<Guid>("ProductDocumentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Version_Description");

                            b1.Property<string>("Keywords")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Version_Keywords");

                            b1.Property<string>("Language")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("OrganisationName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("OrganisationOfficialName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<DateTime?>("StatusSetDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("StatusValue")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("SubTitle")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Version_SubTitle");

                            b1.Property<string>("Title")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Version_Title");

                            b1.Property<string>("Version")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ProductDocumentId");

                            b1.ToTable("ProductDocuments");

                            b1.WithOwner()
                                .HasForeignKey("ProductDocumentId");
                        });

                    b.Navigation("Classification")
                        .IsRequired();

                    b.Navigation("Identifier")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocumentAssignment", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.ProductDocument", "ProductDocument")
                        .WithMany("DocumentAssignments")
                        .HasForeignKey("ProductDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMEAdapter.Domain.Entities.Product", "Product")
                        .WithMany("DocumentAssignments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductDocument");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalData", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TechnicalDataTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalDataProperty", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalData", "ProductTechnicalData")
                        .WithMany("Properties")
                        .HasForeignKey("ProductTechnicalDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateProperty", "TemplateProperty")
                        .WithMany()
                        .HasForeignKey("TemplatePropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductTechnicalData");

                    b.Navigation("TemplateProperty");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateProperty", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateSection", "Section")
                        .WithMany("Properties")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateSection", b =>
                {
                    b.HasOne("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TechnicalDataTemplate", "Template")
                        .WithMany("Sections")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.Product", b =>
                {
                    b.Navigation("DocumentAssignments");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductDocument", b =>
                {
                    b.Navigation("DocumentAssignments");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.ProductTechnicalData", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TechnicalDataTemplate", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SMEAdapter.Domain.Entities.ProductTechnicalDataTemplate.TemplateSection", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
